---
- name: Install required packages
  tags: system
  ansible.builtin.apt:
    name: ["acl", "firewalld"]
    state: present
    update_cache: true

- name: Ensure firewalld is enabled and running
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started
